# Generated by Django 6.0.4 on 2026-04-27 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('beklemede', 'Beklemede'), ('devam', 'Devam Ediyor'), ('tamam', 'Tamamlandı')], default='beklemede', max_length=20)),
                ('priority', models.CharField(choices=[('dusuk', 'Düşük'), ('orta', 'Orta'), ('yuksek', 'Yüksek')], max_length=20)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.unit')),
            ],
        ),
    ]
