# Generated by Django 6.0.4 on 2026-04-27 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='tasks.unit')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='tasks.task')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='tasks.unit')),
            ],
        ),
    ]
